#!/bin/bash

# Welcome to my Study Guide script. Users are able to add question, they can specify if its 
# multiple choice, or true/false. There will be a score system so users can keep track 
# how many they got right. Ive sectioned the script into parts

# The parts are:

# - Initialize Variables
#   Ex: score = 0, total_question =0

# - Load True/False Questions
# - Load Multiple Choice Questions
# - Show Quiz
# - Add questions
# - Display Score

# - Ask True or False Questions
# - Ask Multiple Choice Questions

# - Error Handling
# Main Menu


# ---------------------------------------------------------------------------------------
# Step 1: Check and Create the txt files, and load question it

# Create the True/False txt file
if [ ! -f "True_False_questions.txt" ]; then
	touch True_False_Questions.txt
	echo "Created the True/False txt File"
else
	echo "True/False txt file already created"
fi

# Create the Multiple Choice txt File

if [ ! -f "Multiple_Choice_questions.txt" ]; then
	touch Multiple_Choice_questions.txt
	echo "Created the Multiple Choice txt File"
else
	echo "Multiple Choice txt file already created"
fi

# ---------------------------------------------------------------------------------------
# Step 2: Initialize Variables
 
  score = 0
  true_false_file="True_False_questions.txt"
  multiple_choice_file="Multiple_Choice_questions.txt"


# --------------------------------------------------------------------------------------
# Step 3: Load Question from Files
# # Write functions to load questions from the .txt files

load_questions() {

   # I plan on loading the questions from the txt file into these array 
   true_false_questions=()
   multiple_choice_questions=()
   
   # Load True or False questions from the file
   while IFS= read -r line; do
	   # read the first line and let line hold onto it
	   # += adds it to the array 
	   true_false_questions+=("$line")
   done < "$true_false_file"

   # Load Muctiple Choice questions from the file

   while IFS= read -r line; do
	   multiple_choice_question+=("$line")
   done < "$multiple_choice_file"

   # basically reading the txt file and outputting it in the array 
     
}
# ---------------------------------------------------------------------------------------
# Step 4: Display and Ask Questions
# ---------------------------------------------------------------------------------------
# Step 5: Handle True/False Questions
# ---------------------------------------------------------------------------------------
# Step 6: Handle Multiple Choice Questions
# ---------------------------------------------------------------------------------------
# Step 7: Add Questions
# ---------------------------------------------------------------------------------------
# Step 8: Display Score
# ---------------------------------------------------------------------------------------
# Step 9: Main Menu Function
# ---------------------------------------------------------------------------------------
# Step 10: Call the Scrip
