#!/bin/bash

# Welcome to my Study Guide script. Users are able to add question, they can specify if its 
# multiple choice, or true/false. There will be a score system so users can keep track 
# how many they got right. Ive sectioned the script into parts

# The parts are:

# - Initialize Variables
#   Ex: score = 0, total_question =0

# - Load True/False Questions
# - Load Multiple Choice Questions
# - Show Quiz
# - Add questions
# - Display Score

# - Ask True or False Questions
# - Ask Multiple Choice Questions

# - Error Handling
# Main Menu
# ---------------------------------------------------------------------------------------
# Step 1: Check and Create the txt files, and load question it

# Create the True/False txt file
if [ ! -f "True_False_questions.txt" ]; then
	touch True_False_Questions.txt
	echo "Created the True/False txt File"
fi

# Create the Multiple Choice txt File

if [ ! -f "Multiple_Choice_questions.txt" ]; then
	touch Multiple_Choice_questions.txt
	echo "Created the Multiple Choice txt File"
fi

# ---------------------------------------------------------------------------------------
# Step 2: Initialize Variables
 
  score = 0
  true_false_file="Tru_False_questions.txt"
  multiple_choice="Multiple_Choice_questions.txt"

# ---------------------------------------------------------------------------------------
# Step 3: Define the Main Menu Functions
# ---------------------------------------------------------------------------------------
# Step 4: Load Question from Files
# # Write functions to load questions from the .txt files
# ---------------------------------------------------------------------------------------
# Step 5: Display and Ask questions
# ---------------------------------------------------------------------------------------
# Step 6: Handle True/False Questions
# ---------------------------------------------------------------------------------------
# Step 7: Handle Multiple Choice Questions
# ---------------------------------------------------------------------------------------
# Step 8: Add Questions
# ---------------------------------------------------------------------------------------
# Step 9: Display Score
# ---------------------------------------------------------------------------------------
# Step 10: Call the Scrip
